### ISSUE TITLE
Prompt before deleting an address.

### ISSUE THREAD

**Issue by engr-miraculous** [X-CASH-official/android-wallet#7]
As a user am used to getting that extra worning, when am about taking a potentially bad action.
So am suggesting that there should be a dialogue box telling me that I should ensure I have my keys before deleting my address.

**Comment by zachhildreth** [comment]
Hi, This issue should be fixed on the next release and is currently in the develop branch under commit d3364cb02a3e5f8908ac18e4adf7565315042d9c
